### ISSUE TITLE
eval.c bug?

### ISSUE THREAD

**Issue by hwliu11** [lfarizav/NSGA-III#1]
in file eval.c line 51~54,it will mistype?
		for (k=0; j<neqcon; k++)
		{
		        ind->equality_constr_violation += abs(ind->equality_constr[j]);
		}
Maybe 
		for (k=0; k<neqcon; k++)
		{
		        ind->equality_constr_violation += abs(ind->equality_constr[k]);
		}

**Comment by lfarizav** [comment]
Thank you so much Hwliu11. You are right.
I will modify it immediately.
Best regards,
