### ISSUE TITLE
fillnds.c visit out of range

### ISSUE THREAD

**Issue by hwliu11** [lfarizav/NSGA-III#2]
In file fillnds.c line 323-326
    for (l=0; l<archieve_and_front_sizes; l++)
    {
        associate(&selection_pop->ind[l],&new_pop->ind[l],l, archieve_size,0,factorial+factorial_inside+last_gen_adaptive_refpoints_number);
    }
the value archieve_and_front_sizes can be greater than new_pop->ind size,because selection_pop->ind size is 2*popsize,but new_pop->ind size is popsize. Why it's not crash, I think it visit volitation memory nut no memory check.I replace ind with std::vector,it will crash because of out of range.The function associate not use new_pop->ind,so can i del it?

**Comment by lfarizav** [comment]
I am checking this issue.

**Comment by lfarizav** [comment]
It does not crash because the associate function does not use it.
Yes, you can delete new_pop->ind from associate function.
By the way, it was already changed.

Thanks for your questions
